import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

BRAND_COLOR = colors.HexColor("#1a3c6e")
RULE_COLOR = colors.HexColor("#cccccc")


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("TitleStyle", parent=base["Title"], fontSize=18, textColor=BRAND_COLOR, spaceAfter=4),
        "section": ParagraphStyle("SectionHeader", parent=base["Heading2"], fontSize=13, textColor=BRAND_COLOR, spaceBefore=12, spaceAfter=4),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10.5, leading=15),
        "bullet": ParagraphStyle("Bullet", parent=base["Normal"], fontSize=10.5, leading=15, leftIndent=12),
        "meta": ParagraphStyle("Meta", parent=base["Normal"], fontSize=10, textColor=colors.HexColor("#555555")),
        "footer": ParagraphStyle("Footer", parent=base["Normal"], fontSize=8, textColor=colors.grey, alignment=TA_CENTER),
    }


def generate_pdf(student, narrative, output_path):
    """Renders a deterministic PDF template around the AI-generated narrative JSON."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    styles = _styles()

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
    )

    elements = []
    elements.append(Paragraph("STUDENT ASSESSMENT REPORT", styles["title"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=BRAND_COLOR))
    elements.append(Spacer(1, 8))

    meta_table = Table(
        [
            [f"Name: {student.get('name', '')}", f"Date: {datetime.now().strftime('%d/%m/%Y')}"],
            [f"Class: {student.get('class', '')}", f"ID: {student.get('id', '')}"],
        ],
        colWidths=[240, 240],
    )
    meta_table.setStyle(TableStyle([("FONTSIZE", (0, 0), (-1, -1), 10), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)]))
    elements.append(meta_table)
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("SUBJECT SCORES", styles["section"]))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=RULE_COLOR))
    score_rows = [["Subject", "Score"]] + [[subject, str(score)] for subject, score in student.get("scores", {}).items()]
    score_table = Table(score_rows, colWidths=[300, 100])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), BRAND_COLOR),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.5, RULE_COLOR),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    elements.append(score_table)
    elements.append(Spacer(1, 4))
    elements.append(
        Paragraph(
            f"Percentile: {student.get('percentile', 'N/A')} &nbsp;|&nbsp; Attendance: {student.get('attendance', 'N/A')}%",
            styles["meta"],
        )
    )
    elements.append(Spacer(1, 6))

    def section(title, content):
        elements.append(Paragraph(title, styles["section"]))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=RULE_COLOR))
        if isinstance(content, list):
            for item in content:
                elements.append(Paragraph(f"&bull; {item}", styles["bullet"]))
        else:
            elements.append(Paragraph(content, styles["body"]))

    section("PERFORMANCE SUMMARY", narrative.get("summary", ""))
    section("STRENGTHS", narrative.get("strengths", []))
    section("IMPROVEMENT AREAS", narrative.get("improvements", []))
    section("RECOMMENDATIONS", narrative.get("recommendations", []))
    section("CAREER GUIDANCE", narrative.get("career_guidance", ""))
    section("OVERALL INSIGHT", narrative.get("overall_insight", ""))

    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=1, color=BRAND_COLOR))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph("Generated by AI Assessment System", styles["footer"]))

    doc.build(elements)
    return output_path
